# Generated by Django 3.2.5 on 2021-07-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='active_bid',
            field=models.BooleanField(default=False),
        ),
    ]
