# Generated by Django 3.2.5 on 2021-07-31 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_active_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='active_bid',
        ),
    ]
