# Generated by Django 3.2.5 on 2021-07-28 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidder',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.products'),
        ),
        migrations.AddField(
            model_name='products',
            name='bidPrice',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
