# Generated by Django 3.2.5 on 2021-07-29 10:46

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210728_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='thumb',
            field=models.ImageField(blank=True, upload_to=main.models.upload_location),
        ),
    ]
